### ISSUE TITLE
dostuff_switch_lights.py could use MQTT to send commands to goLightCtrl

### ISSUE THREAD

**Issue by nicoonoclaste** [realraum/door_and_sensors#1]
This is required to remove the HTTP interface from goLightCtrl: realraum/deckenlichtschalter#1.

**Comment by btittelbach** [comment]
Adding control via MQTT to goLightCtrl could be a nice feature. Will probably happen in the feature.

We won't get rid of the http interface on goLightCtrl that easily however, since we want to continue to support web clients which don't support websocket. Also you know that Mosquitto as per Debian does not come with websocket compiled in. Also I'm against ever enabling that, since I don't feel comfortable exposing a central point of failure component to web browsers and the additional load that would incur.

**Comment by PeterTheOne** [comment]
> We won't get rid of the http interface on goLightCtrl that easily however, since we want to continue to support web clients which don't support websocket.

http://caniuse.com/#feat=websockets

**Comment by nicoonoclaste** [comment]
According to what @PeterTheOne linked, at least 90% of web browsers support this.
I think it wouldn't be unreasonable to not support outdated browsers for `licht.realraum.at`
